package com.example.flutter_seuic_uhf_plugin_sdk.constant;

public interface Channel {
    String METHOD_CHANNEL_OPEN = "METHOD_CHANNEL_OPEN";
    String METHOD_CHANNEL_CLOSE = "METHOD_CHANNEL_CLOSE";
    String METHOD_CHANNEL_VERSION = "METHOD_CHANNEL_VERSION";
    String METHOD_CHANNEL_TEMP = "METHOD_CHANNEL_TEMP";
    String METHOD_CHANNEL_POWER = "METHOD_CHANNEL_POWER";
    String EVENT_CHANNEL_SCANNER_UHF = "EVENT_CHANNEL_SCANNER_UHF";
}
